version: "3"

volumes:
  bundle:
services:
  app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - 3000:3000
    network_mode: "host"
    volumes:
      - ./:/opt/app
      - bundle:/usr/local/bundle
